version: "3.9"

services:
  transaction-db:
    image: postgres:16
    network_mode: host
    container_name: ajla-db
      #ports:
      #- "2354:5432"   # host access only
    environment:
      POSTGRES_USER: ajla_user
      POSTGRES_PASSWORD: test123
        #POSTGRES_PORT: 5432
      POSTGRES_DB: ajla_db
    command: ["postgres", "-c", "max_connections=1000"]
    volumes:
      - transactionData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ajla_user -d ajla_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  api:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: ajla-api:1.0.0
    container_name: ajla-api
    network_mode: host
    #build: .
    #ports:
    # - "8080:8080"
    environment:
      DATABASE_URL: postgresql://ajla_user:test123@127.0.0.1:5432/ajla_db
      PORT: 8080
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --proxy-headers"
    depends_on:
      transaction-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  transactionData:
